apiVersion: apps/v1
kind: Deployment
metadata:
  name: kryptic-eks-dev
  annotations: # Prometheus Application level monitoring
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"  # Your app's metrics port
    prometheus.io/path: "/metrics"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kryptic-eks-dev
  template:
    metadata:
      labels:
        app: kryptic-eks-dev
    spec:
      serviceAccountName: ecr-puller
      containers:
      - name: kryptic-eks-dev
        image: 865494649634.dkr.ecr.us-east-1.amazonaws.com/kryptic-ecr-repo-dev:${GITHUB_SHA}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
