apiVersion: v1
kind: Service
metadata:
  name: kryptic-eks-dev-service
spec:
  type: LoadBalancer
  selector:
    app: kryptic-eks-dev-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000