name: Kryptic-Terraform-EKS-DevOps
on:
  push:
    branches: [develop]
    
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: |
          echo "Changed infrastructure code"

  Deploy:
    runs-on: ubuntu-latest
    needs: deploy-infra  # Wait for infra if both changed
    steps:
    
    - name: Login to ECR
      uses: docker/login-action@v3
      with:
        registry: 865494649634.dkr.ecr.us-east-1.amazonaws.com
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Build 
      working-directory: /home/runner/work/Terraform-eks-devops/application
      run: |
          echo "Navigate to the application directory"
          echo "Confirm directory" 
          ls 
          echo "Build the Docker image, tagging it with the current GitHub commit SHA"
          docker build -t kryptic-eks-devops:${{ github.sha }} .
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      with:
          image-ref: 'kryptic-eks-devops:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
          sarif_file: 'trivy-results.sarif'

    - name: Push image to ECR if scan pass
      run: |
       # Tag the Docker image for the Amazon ECR repository using the same GitHub commit SHA
        docker tag kryptic-eks-devops:${{ github.sha }} 865494649634.dkr.ecr.us-east-1.amazonaws.com/kryptic-eks-devops:${{ github.sha }}
       # Tag the Docker image for the Amazon ECR repository using the same GitHub commit SHA
        docker push 865494649634.dkr.ecr.us-east-1.amazonaws.com/kryptic-eks-devops:${{ github.sha }}
    

      
