name: Kryptic-Terraform-EKS-DevOps
on:
  push:
    branches: [develop]
    
jobs:
  Build:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to ECR
      uses: docker/login-action@v3
      with:
        registry: 865494649634.dkr.ecr.us-east-1.amazonaws.com
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Build 
      run: |
          echo "Navigate to the application directory"
          echo "Confirm directory"
          pwd && ls -al
          cd application
          ls 
          echo "Build the Docker image, tagging it with the current GitHub commit SHA"
          docker build -t kryptic-eks-devops:${{ github.sha }} .
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      with:
          image-ref: 'kryptic-eks-devops:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

    - name: Push image to ECR if scan pass
      run: |
       # Tag the Docker image for the Amazon ECR repository using the same GitHub commit SHA
        docker tag kryptic-eks-devops:${{ github.sha }} 865494649634.dkr.ecr.us-east-1.amazonaws.com/kryptic-eks-devops:${{ github.sha }}
       # Tag the Docker image for the Amazon ECR repository using the same GitHub commit SHA
        docker push 865494649634.dkr.ecr.us-east-1.amazonaws.com/kryptic-eks-devops:${{ github.sha }}

  K8S-Pull:
      runs-on: ubuntu-latest
      needs: Build
      steps:
      - uses: actions/checkout@v4
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 865494649634.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Apply deployment 
        run: |
            echo "Navigate to the application directory"
            echo "Confirm directory"
            pwd && ls -al
            cd infrastructure
      - name: Deploy to Kubernetes
        run: |
          sed -i "s/\${GITHUB_SHA}/${{ github.sha }}/g" ./k8/deployment.yaml
          kubectl apply -f ./k8s
          
            
      